name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [ '17', '21' ]
    permissions:
      contents: read

    env:
      DISPLAY: ":99.0"

    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        options: --shm-size 2g

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Start Xvfb
        if: runner.os == 'Linux'
        run: Xvfb $DISPLAY -ac -screen 0 1600x1200x24 > /dev/null 2>&1 &

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: gradle build
